/**
 * SEED-RETTER — 25 kuraterede hverdagsretter til MVP'en.
 * ======================================================
 * Formål: at give variation nok til ægte brugertest uden at ændre matcher eller kontrakt.
 * Bemærk især:
 *  - bærende vs. fleksibel pr. ingrediens (det der gør løftet holdbart)
 *  - steps: én handling pr. trin, imperativ, ingen kokke-lyrik
 *  - approved: true = håndgodkendt og klar til forslag
 */

import type { Recipe } from "../../types/contracts";

export const SEED_RECIPES: Recipe[] = [
  {
    id: "one-pot-pasta-kylling",
    name: "One-pot pasta med kylling",
    minutes: 25,
    category: "pasta",
    childFriendly: true,
    allergens: ["gluten", "laktose"],
    ingredients: [
      { ingredientId: "kyllingebryst", displayName: "kyllingebryst", role: "bærende", amountText: "400 g" },
      { ingredientId: "pasta_skruer", displayName: "pastaskruer", role: "bærende", amountText: "300 g" },
      { ingredientId: "floede", displayName: "fløde", role: "bærende", amountText: "2,5 dl" },
      { ingredientId: "loeg", displayName: "løg", role: "fleksibel", amountText: "1 stk" },
      { ingredientId: "hvidloeg", displayName: "hvidløg", role: "fleksibel", amountText: "2 fed" },
      { ingredientId: "revet_ost", displayName: "revet ost", role: "fleksibel", amountText: "en håndfuld" },
    ],
    steps: [
      "Skær kyllingen i tern.",
      "Brun kyllingen i en stor gryde, 3-4 minutter.",
      "Tilsæt løg og hvidløg, steg 2 minutter.",
      "Hæld pasta, fløde og 4 dl vand i gryden.",
      "Lad det simre under låg i 12 minutter og rør et par gange.",
      "Smag til med salt og peber, top med ost.",
    ],
    approved: true,
  },
  {
    id: "kylling-i-karry",
    name: "Kylling i karry med ris",
    minutes: 30,
    category: "ris",
    childFriendly: true,
    allergens: ["laktose"],
    ingredients: [
      { ingredientId: "kyllingebryst", displayName: "kyllingebryst", role: "bærende", amountText: "400 g" },
      { ingredientId: "kokosmaelk", displayName: "kokosmælk", role: "bærende", amountText: "1 dåse" },
      { ingredientId: "ris", displayName: "ris", role: "bærende", amountText: "3 dl" },
      { ingredientId: "karrypasta", displayName: "karry", role: "bærende", amountText: "1 spsk" },
      { ingredientId: "loeg", displayName: "løg", role: "fleksibel", amountText: "1 stk" },
      { ingredientId: "gulerod", displayName: "gulerødder", role: "fleksibel", amountText: "2 stk" },
      { ingredientId: "floede", displayName: "fløde", role: "fleksibel", amountText: "1 dl" },
    ],
    steps: [
      "Sæt risene over efter anvisningen på posen.",
      "Skær kylling, løg og gulerødder i mundrette stykker.",
      "Steg løg og karry i gryden 1 minut, til det dufter.",
      "Tilsæt kylling og brun den kort.",
      "Hæld kokosmælk ved og lad det simre 12-15 minutter.",
      "Smag til og servér over risene.",
    ],
    approved: true,
  },
  {
    id: "pandekage-taco-torsdag",
    name: "Madpandekager med oksekødsfyld",
    minutes: 35,
    category: "pande",
    childFriendly: true,
    allergens: ["gluten", "laktose", "æg"],
    ingredients: [
      { ingredientId: "hakket_oksekoed", displayName: "hakket oksekød", role: "bærende", amountText: "400 g" },
      { ingredientId: "aeg", displayName: "æg", role: "bærende", amountText: "3 stk" },
      { ingredientId: "maelk", displayName: "mælk", role: "bærende", amountText: "4 dl" },
      { ingredientId: "hvedemel", displayName: "hvedemel", role: "bærende", amountText: "250 g" },
      { ingredientId: "tomat_haakket_daase", displayName: "hakkede tomater", role: "fleksibel", amountText: "1 dåse" },
      { ingredientId: "revet_ost", displayName: "revet ost", role: "fleksibel", amountText: "til topping" },
      { ingredientId: "peberfrugt", displayName: "peberfrugt", role: "fleksibel", amountText: "1 stk" },
    ],
    steps: [
      "Pisk æg, mælk, mel og en knivspids salt til pandekagedej.",
      "Brun kødet på panden.",
      "Tilsæt hakkede tomater og peberfrugt, lad det simre 10 minutter.",
      "Bag pandekagerne imens.",
      "Fyld pandekagerne med kød, top med ost og rul sammen.",
    ],
    approved: true,
  },
  {
    id: "broccolisuppe-med-broed",
    name: "Broccolisuppe med brød",
    minutes: 20,
    category: "suppe",
    childFriendly: false,
    allergens: ["laktose"],
    ingredients: [
      { ingredientId: "broccoli", displayName: "broccoli", role: "bærende", amountText: "1 stort hoved" },
      { ingredientId: "kartofler", displayName: "kartofler", role: "bærende", amountText: "3 stk" },
      { ingredientId: "loeg", displayName: "løg", role: "bærende", amountText: "1 stk" },
      { ingredientId: "floede", displayName: "fløde", role: "fleksibel", amountText: "1 dl" },
      { ingredientId: "bouillon_terning", displayName: "bouillonterning", role: "fleksibel", amountText: "1 stk" },
    ],
    steps: [
      "Hak løg, kartofler og broccoli groft.",
      "Svits løget i gryden 2 minutter.",
      "Tilsæt kartofler, broccoli, bouillon og vand til det lige dækker.",
      "Kog 12 minutter, til kartoflerne er møre.",
      "Blend suppen, rør fløden i og smag til.",
    ],
    approved: true,
  },
  {
    id: "spaghetti-koedsovs-klassisk",
    name: "Spaghetti med kødsovs",
    minutes: 30,
    category: "pasta",
    childFriendly: true,
    allergens: ["gluten"],
    ingredients: [
      { ingredientId: "hakket_oksekoed", displayName: "hakket oksekød", role: "bærende", amountText: "400 g" },
      { ingredientId: "spaghetti", displayName: "spaghetti", role: "bærende", amountText: "300 g" },
      { ingredientId: "tomat_haakket_daase", displayName: "hakkede tomater", role: "bærende", amountText: "2 dåser" },
      { ingredientId: "loeg", displayName: "løg", role: "fleksibel", amountText: "1 stk" },
      { ingredientId: "hvidloeg", displayName: "hvidløg", role: "fleksibel", amountText: "2 fed" },
      { ingredientId: "gulerod", displayName: "gulerod", role: "fleksibel", amountText: "1 stk, revet" },
      { ingredientId: "parmesan", displayName: "parmesan", role: "fleksibel", amountText: "til servering" },
    ],
    steps: [
      "Svits løg og hvidløg i en gryde.",
      "Brun kødet ved høj varme.",
      "Tilsæt tomater og revet gulerod, lad sovsen simre 15 minutter.",
      "Kog spaghettien imens.",
      "Smag sovsen til og servér med parmesan.",
    ],
    approved: true,
  },
  {
    id: "cremet-pesto-pasta-kylling",
    name: "Cremet pesto-pasta med kylling",
    minutes: 25,
    category: "pasta",
    childFriendly: true,
    allergens: ["gluten", "laktose"],
    ingredients: [
      { ingredientId: "kyllingebryst", displayName: "kyllingebryst", role: "bærende", amountText: "400 g" },
      { ingredientId: "pasta_skruer", displayName: "pastaskruer", role: "bærende", amountText: "300 g" },
      { ingredientId: "pesto", displayName: "pesto", role: "bærende", amountText: "3 spsk" },
      { ingredientId: "floede", displayName: "fløde", role: "fleksibel", amountText: "1 dl" },
      { ingredientId: "broccoli", displayName: "broccoli", role: "fleksibel", amountText: "1/2 hoved" },
      { ingredientId: "parmesan", displayName: "parmesan", role: "fleksibel", amountText: "til toppen" },
    ],
    steps: [
      "Kog pastaen efter anvisningen på pakken.",
      "Steg kyllingen gylden på en stor pande.",
      "Tilsæt broccoli i små buketter og steg 3 minutter.",
      "Vend pesto og fløde sammen med pastaen.",
      "Top med parmesan og servér med det samme.",
    ],
    approved: true,
  },
  {
    id: "bacon-broccoli-pasta",
    name: "Baconpasta med broccoli",
    minutes: 20,
    category: "pasta",
    childFriendly: true,
    allergens: ["gluten", "laktose"],
    ingredients: [
      { ingredientId: "pasta_skruer", displayName: "pastaskruer", role: "bærende", amountText: "300 g" },
      { ingredientId: "bacon", displayName: "bacon", role: "bærende", amountText: "200 g" },
      { ingredientId: "broccoli", displayName: "broccoli", role: "bærende", amountText: "1 hoved" },
      { ingredientId: "floede", displayName: "fløde", role: "fleksibel", amountText: "1 dl" },
      { ingredientId: "parmesan", displayName: "parmesan", role: "fleksibel", amountText: "til servering" },
    ],
    steps: [
      "Kog pastaen mør.",
      "Steg bacon sprødt på en pande.",
      "Tilsæt broccoli i små buketter og steg 3 minutter.",
      "Vend pasta og fløde sammen på panden.",
      "Top med parmesan og servér.",
    ],
    approved: true,
  },
  {
    id: "pasta-med-skinke-og-floede",
    name: "Pasta med skinke og fløde",
    minutes: 20,
    category: "pasta",
    childFriendly: true,
    allergens: ["gluten", "laktose"],
    ingredients: [
      { ingredientId: "pasta_skruer", displayName: "pastaskruer", role: "bærende", amountText: "300 g" },
      { ingredientId: "skinke", displayName: "skinke", role: "bærende", amountText: "200 g" },
      { ingredientId: "floede", displayName: "fløde", role: "bærende", amountText: "2 dl" },
      { ingredientId: "loeg", displayName: "løg", role: "fleksibel", amountText: "1/2 stk" },
      { ingredientId: "revet_ost", displayName: "revet ost", role: "fleksibel", amountText: "en håndfuld" },
    ],
    steps: [
      "Kog pastaen mør.",
      "Steg løg blødt i lidt smør.",
      "Tilsæt skinke og varm den kort igennem.",
      "Hæld fløde på og lad saucen samle sig 3 minutter.",
      "Vend pastaen i og top med ost.",
    ],
    approved: true,
  },
  {
    id: "spaghetti-med-bacon-og-parmesan",
    name: "Spaghetti med bacon og parmesan",
    minutes: 20,
    category: "pasta",
    childFriendly: true,
    allergens: ["gluten", "laktose", "æg"],
    ingredients: [
      { ingredientId: "spaghetti", displayName: "spaghetti", role: "bærende", amountText: "300 g" },
      { ingredientId: "bacon", displayName: "bacon", role: "bærende", amountText: "200 g" },
      { ingredientId: "aeg", displayName: "æg", role: "bærende", amountText: "3 stk" },
      { ingredientId: "parmesan", displayName: "parmesan", role: "fleksibel", amountText: "50 g" },
      { ingredientId: "hvidloeg", displayName: "hvidløg", role: "fleksibel", amountText: "1 fed" },
    ],
    steps: [
      "Kog spaghettien al dente.",
      "Steg bacon sprødt og tilsæt hvidløg kort.",
      "Pisk æggene sammen i en skål.",
      "Vend den varme pasta med bacon og æg væk fra blusset.",
      "Top med parmesan og servér straks.",
    ],
    approved: true,
  },
  {
    id: "tomatpasta-med-mozzarella-og-peberfrugt",
    name: "Tomatpasta med mozzarella og peberfrugt",
    minutes: 25,
    category: "pasta",
    childFriendly: true,
    allergens: ["gluten", "laktose"],
    ingredients: [
      { ingredientId: "pasta_skruer", displayName: "pastaskruer", role: "bærende", amountText: "300 g" },
      { ingredientId: "tomat_haakket_daase", displayName: "hakkede tomater", role: "bærende", amountText: "1 dåse" },
      { ingredientId: "mozzarella_frisk", displayName: "mozzarella", role: "bærende", amountText: "1 kugle" },
      { ingredientId: "peberfrugt", displayName: "peberfrugt", role: "fleksibel", amountText: "1 stk" },
      { ingredientId: "hvidloeg", displayName: "hvidløg", role: "fleksibel", amountText: "1 fed" },
    ],
    steps: [
      "Kog pastaen mør.",
      "Svits hvidløg og peberfrugt på en pande.",
      "Tilsæt tomater og lad saucen koge 8 minutter.",
      "Vend pastaen i saucen.",
      "Riv mozzarella over og lad den smelte let.",
    ],
    approved: true,
  },
  {
    id: "bagt-pasta-med-oksekoed-og-mozzarella",
    name: "Bagt pasta med oksekød og mozzarella",
    minutes: 35,
    category: "ovn",
    childFriendly: true,
    allergens: ["gluten", "laktose"],
    ingredients: [
      { ingredientId: "hakket_oksekoed", displayName: "hakket oksekød", role: "bærende", amountText: "400 g" },
      { ingredientId: "pasta_skruer", displayName: "pastaskruer", role: "bærende", amountText: "300 g" },
      { ingredientId: "tomat_haakket_daase", displayName: "hakkede tomater", role: "bærende", amountText: "1 dåse" },
      { ingredientId: "mozzarella_frisk", displayName: "mozzarella", role: "fleksibel", amountText: "1 kugle" },
      { ingredientId: "loeg", displayName: "løg", role: "fleksibel", amountText: "1 stk" },
      { ingredientId: "revet_ost", displayName: "revet ost", role: "fleksibel", amountText: "en håndfuld" },
    ],
    steps: [
      "Kog pastaen 2 minutter kortere end pakken siger.",
      "Brun løg og kød i en gryde.",
      "Tilsæt tomater og lad saucen koge 8 minutter.",
      "Vend pasta og sauce sammen i et fad.",
      "Top med mozzarella og ost, bag 15 minutter.",
    ],
    approved: true,
  },
  {
    id: "risfad-med-kylling-og-broccoli",
    name: "Risfad med kylling og broccoli",
    minutes: 35,
    category: "ovn",
    childFriendly: true,
    allergens: ["laktose"],
    ingredients: [
      { ingredientId: "ris", displayName: "ris", role: "bærende", amountText: "3 dl" },
      { ingredientId: "kyllingebryst", displayName: "kyllingebryst", role: "bærende", amountText: "400 g" },
      { ingredientId: "broccoli", displayName: "broccoli", role: "bærende", amountText: "1 hoved" },
      { ingredientId: "floede", displayName: "fløde", role: "fleksibel", amountText: "1 dl" },
      { ingredientId: "bouillon_terning", displayName: "bouillonterning", role: "fleksibel", amountText: "1 stk" },
      { ingredientId: "revet_ost", displayName: "revet ost", role: "fleksibel", amountText: "til toppen" },
    ],
    steps: [
      "Kog risene næsten færdige.",
      "Skær kylling og broccoli i mundrette stykker.",
      "Læg ris, kylling og broccoli i et fad.",
      "Rør fløde, bouillon og 1 dl vand sammen over fadet.",
      "Top med ost og bag 20 minutter.",
    ],
    approved: true,
  },
  {
    id: "stegte-ris-med-kylling-og-aeg",
    name: "Stegte ris med kylling og æg",
    minutes: 20,
    category: "ris",
    childFriendly: true,
    allergens: ["æg"],
    ingredients: [
      { ingredientId: "ris", displayName: "ris", role: "bærende", amountText: "3 dl kogte ris" },
      { ingredientId: "kyllingebryst", displayName: "kyllingebryst", role: "bærende", amountText: "300 g" },
      { ingredientId: "aeg", displayName: "æg", role: "bærende", amountText: "2 stk" },
      { ingredientId: "gulerod", displayName: "gulerod", role: "fleksibel", amountText: "1 stk" },
      { ingredientId: "loeg", displayName: "løg", role: "fleksibel", amountText: "1/2 stk" },
    ],
    steps: [
      "Steg kyllingen gylden på en stor pande.",
      "Tilsæt løg og gulerod i små tern.",
      "Skub fyldet til siden og rør æggene sammen på panden.",
      "Vend risene i og steg det hele 3 minutter.",
      "Smag til med salt og peber.",
    ],
    approved: true,
  },
  {
    id: "fyldte-peberfrugter-med-oksekoed-og-ris",
    name: "Fyldte peberfrugter med oksekød og ris",
    minutes: 40,
    category: "ovn",
    childFriendly: true,
    allergens: ["laktose"],
    ingredients: [
      { ingredientId: "peberfrugt", displayName: "peberfrugt", role: "bærende", amountText: "3 stk" },
      { ingredientId: "hakket_oksekoed", displayName: "hakket oksekød", role: "bærende", amountText: "400 g" },
      { ingredientId: "ris", displayName: "ris", role: "bærende", amountText: "2 dl" },
      { ingredientId: "tomat_haakket_daase", displayName: "hakkede tomater", role: "fleksibel", amountText: "1/2 dåse" },
      { ingredientId: "revet_ost", displayName: "revet ost", role: "fleksibel", amountText: "til toppen" },
      { ingredientId: "loeg", displayName: "løg", role: "fleksibel", amountText: "1/2 stk" },
    ],
    steps: [
      "Kog risene næsten færdige.",
      "Halvér peberfrugterne og fjern kernerne.",
      "Brun kød og løg på en pande.",
      "Vend ris og tomater i kødet.",
      "Fyld peberfrugterne, top med ost og bag 20 minutter.",
    ],
    approved: true,
  },
  {
    id: "tomatgryde-med-oksekoed-og-ris",
    name: "Tomatgryde med oksekød og ris",
    minutes: 30,
    category: "gryde",
    childFriendly: true,
    allergens: [],
    ingredients: [
      { ingredientId: "hakket_oksekoed", displayName: "hakket oksekød", role: "bærende", amountText: "400 g" },
      { ingredientId: "ris", displayName: "ris", role: "bærende", amountText: "3 dl" },
      { ingredientId: "tomat_haakket_daase", displayName: "hakkede tomater", role: "bærende", amountText: "1 dåse" },
      { ingredientId: "loeg", displayName: "løg", role: "fleksibel", amountText: "1 stk" },
      { ingredientId: "gulerod", displayName: "gulerod", role: "fleksibel", amountText: "1 stk" },
    ],
    steps: [
      "Sæt risene over.",
      "Brun kød og løg i en gryde.",
      "Tilsæt gulerod i små tern og steg 2 minutter.",
      "Hæld tomater ved og lad gryden simre 12 minutter.",
      "Servér gryden over risene.",
    ],
    approved: true,
  },
  {
    id: "kartoffelgratin-med-skinke-og-ost",
    name: "Kartoffelgratin med skinke og ost",
    minutes: 40,
    category: "ovn",
    childFriendly: true,
    allergens: ["laktose"],
    ingredients: [
      { ingredientId: "kartofler", displayName: "kartofler", role: "bærende", amountText: "800 g" },
      { ingredientId: "skinke", displayName: "skinke", role: "bærende", amountText: "200 g" },
      { ingredientId: "floede", displayName: "fløde", role: "bærende", amountText: "2,5 dl" },
      { ingredientId: "revet_ost", displayName: "revet ost", role: "fleksibel", amountText: "en håndfuld" },
      { ingredientId: "hvidloeg", displayName: "hvidløg", role: "fleksibel", amountText: "1 fed" },
    ],
    steps: [
      "Skær kartoflerne i tynde skiver.",
      "Fordel kartofler og skinke lagvis i et fad.",
      "Hæld fløde over og gnid fadet med hvidløg først.",
      "Top med ost.",
      "Bag gratinen 30 minutter, til kartoflerne er møre.",
    ],
    approved: true,
  },
  {
    id: "kylling-i-fad-med-kartofler-og-floede",
    name: "Kylling i fad med kartofler og fløde",
    minutes: 40,
    category: "ovn",
    childFriendly: true,
    allergens: ["laktose"],
    ingredients: [
      { ingredientId: "kyllingebryst", displayName: "kyllingebryst", role: "bærende", amountText: "400 g" },
      { ingredientId: "kartofler", displayName: "kartofler", role: "bærende", amountText: "700 g" },
      { ingredientId: "floede", displayName: "fløde", role: "bærende", amountText: "2 dl" },
      { ingredientId: "loeg", displayName: "løg", role: "fleksibel", amountText: "1 stk" },
      { ingredientId: "peberfrugt", displayName: "peberfrugt", role: "fleksibel", amountText: "1 stk" },
    ],
    steps: [
      "Skær kartofler og kylling i mundrette stykker.",
      "Fordel det i et fad med løg og peberfrugt.",
      "Hæld fløde over og krydr godt.",
      "Bag fadet 30 minutter, til kyllingen er gennemstegt.",
      "Rør rundt halvvejs.",
    ],
    approved: true,
  },
  {
    id: "kartoffelpande-med-bacon-og-loeg",
    name: "Kartoffelpande med bacon og løg",
    minutes: 25,
    category: "pande",
    childFriendly: true,
    allergens: [],
    ingredients: [
      { ingredientId: "kartofler", displayName: "kartofler", role: "bærende", amountText: "700 g" },
      { ingredientId: "bacon", displayName: "bacon", role: "bærende", amountText: "200 g" },
      { ingredientId: "loeg", displayName: "løg", role: "fleksibel", amountText: "1 stk" },
      { ingredientId: "aeg", displayName: "æg", role: "fleksibel", amountText: "2 stk" },
    ],
    steps: [
      "Skær kartoflerne i små tern.",
      "Steg bacon sprødt på panden.",
      "Tilsæt kartofler og løg og steg dem møre.",
      "Slå æggene over til sidst, hvis du vil samle panden.",
      "Servér direkte fra panden.",
    ],
    approved: true,
  },
  {
    id: "bagte-kartofler-med-baconcreme",
    name: "Bagte kartofler med baconcreme",
    minutes: 45,
    category: "kartoffel",
    childFriendly: true,
    allergens: ["laktose"],
    ingredients: [
      { ingredientId: "kartofler", displayName: "kartofler", role: "bærende", amountText: "4 store stk" },
      { ingredientId: "bacon", displayName: "bacon", role: "bærende", amountText: "150 g" },
      { ingredientId: "creme_fraiche", displayName: "creme fraiche", role: "bærende", amountText: "2 dl" },
      { ingredientId: "loeg", displayName: "løg", role: "fleksibel", amountText: "1/2 stk finthakket" },
      { ingredientId: "agurk", displayName: "agurk", role: "fleksibel", amountText: "1/4 stk" },
    ],
    steps: [
      "Bag kartoflerne møre i ovnen.",
      "Steg bacon sprødt på en pande.",
      "Rør creme fraiche sammen med løg og små tern af agurk.",
      "Flæk kartoflerne og fyld dem med baconcremen.",
      "Servér med det samme.",
    ],
    approved: true,
  },
  {
    id: "aeggekage-med-bacon-og-loeg",
    name: "Æggekage med bacon og løg",
    minutes: 20,
    category: "pande",
    childFriendly: true,
    allergens: ["laktose", "æg"],
    ingredients: [
      { ingredientId: "aeg", displayName: "æg", role: "bærende", amountText: "6 stk" },
      { ingredientId: "bacon", displayName: "bacon", role: "bærende", amountText: "150 g" },
      { ingredientId: "maelk", displayName: "mælk", role: "fleksibel", amountText: "1 dl" },
      { ingredientId: "loeg", displayName: "løg", role: "fleksibel", amountText: "1/2 stk" },
      { ingredientId: "kartofler", displayName: "kartofler", role: "fleksibel", amountText: "2 kogte stk" },
    ],
    steps: [
      "Steg bacon sprødt på panden.",
      "Tilsæt løg og kartofler i skiver.",
      "Pisk æg og mælk sammen.",
      "Hæld æggemassen over panden og steg ved lav varme.",
      "Fold æggekagen let sammen og servér.",
    ],
    approved: true,
  },
  {
    id: "omelet-med-skinke-og-ost",
    name: "Omelet med skinke og ost",
    minutes: 15,
    category: "pande",
    childFriendly: true,
    allergens: ["laktose", "æg"],
    ingredients: [
      { ingredientId: "aeg", displayName: "æg", role: "bærende", amountText: "5 stk" },
      { ingredientId: "skinke", displayName: "skinke", role: "bærende", amountText: "150 g" },
      { ingredientId: "revet_ost", displayName: "revet ost", role: "fleksibel", amountText: "en håndfuld" },
      { ingredientId: "maelk", displayName: "mælk", role: "fleksibel", amountText: "1 sjat" },
      { ingredientId: "peberfrugt", displayName: "peberfrugt", role: "fleksibel", amountText: "1/2 stk" },
    ],
    steps: [
      "Pisk æg og mælk sammen.",
      "Steg peberfrugt kort på panden.",
      "Hæld æggemassen på og lad den sætte sig.",
      "Fordel skinke og ost over omeletten.",
      "Fold den sammen og servér.",
    ],
    approved: true,
  },
  {
    id: "gulerodssuppe-med-floede",
    name: "Gulerodssuppe med fløde",
    minutes: 25,
    category: "suppe",
    childFriendly: true,
    allergens: ["laktose"],
    ingredients: [
      { ingredientId: "gulerod", displayName: "gulerødder", role: "bærende", amountText: "6 stk" },
      { ingredientId: "kartofler", displayName: "kartofler", role: "bærende", amountText: "2 stk" },
      { ingredientId: "loeg", displayName: "løg", role: "bærende", amountText: "1 stk" },
      { ingredientId: "floede", displayName: "fløde", role: "fleksibel", amountText: "1 dl" },
      { ingredientId: "bouillon_terning", displayName: "bouillonterning", role: "fleksibel", amountText: "1 stk" },
    ],
    steps: [
      "Skær gulerødder, kartofler og løg groft.",
      "Svits løget i lidt smør.",
      "Tilsæt resten, bouillon og vand til det lige dækker.",
      "Kog 15 minutter, til grønt er mørt.",
      "Blend suppen og rør fløden i.",
    ],
    approved: true,
  },
  {
    id: "tomatsuppe-med-mozzarella",
    name: "Tomatsuppe med mozzarella",
    minutes: 20,
    category: "suppe",
    childFriendly: true,
    allergens: ["laktose"],
    ingredients: [
      { ingredientId: "tomat_haakket_daase", displayName: "hakkede tomater", role: "bærende", amountText: "2 dåser" },
      { ingredientId: "loeg", displayName: "løg", role: "bærende", amountText: "1 stk" },
      { ingredientId: "bouillon_terning", displayName: "bouillonterning", role: "bærende", amountText: "1 stk" },
      { ingredientId: "mozzarella_frisk", displayName: "mozzarella", role: "fleksibel", amountText: "1 kugle" },
      { ingredientId: "hvidloeg", displayName: "hvidløg", role: "fleksibel", amountText: "1 fed" },
    ],
    steps: [
      "Svits løg og hvidløg i en gryde.",
      "Tilsæt tomater, bouillon og 4 dl vand.",
      "Lad suppen simre 12 minutter.",
      "Blend den glat.",
      "Top med mozzarella i stykker ved servering.",
    ],
    approved: true,
  },
  {
    id: "madpandekager-med-kylling-og-peberfrugt",
    name: "Madpandekager med kylling og peberfrugt",
    minutes: 35,
    category: "brød_wraps",
    childFriendly: true,
    allergens: ["gluten", "laktose", "æg"],
    ingredients: [
      { ingredientId: "aeg", displayName: "æg", role: "bærende", amountText: "3 stk" },
      { ingredientId: "maelk", displayName: "mælk", role: "bærende", amountText: "4 dl" },
      { ingredientId: "hvedemel", displayName: "hvedemel", role: "bærende", amountText: "250 g" },
      { ingredientId: "kyllingebryst", displayName: "kyllingebryst", role: "bærende", amountText: "350 g" },
      { ingredientId: "peberfrugt", displayName: "peberfrugt", role: "fleksibel", amountText: "1 stk" },
      { ingredientId: "smoereost", displayName: "smøreost", role: "fleksibel", amountText: "2 spsk" },
    ],
    steps: [
      "Pisk pandekagedejen sammen og bag tynde pandekager.",
      "Steg kylling og peberfrugt i strimler på en pande.",
      "Smør pandekagerne med smøreost.",
      "Fordel fyldet og rul dem sammen.",
      "Servér dem lune.",
    ],
    approved: true,
  },
  {
    id: "kold-pastasalat-med-kylling-og-agurk",
    name: "Kold pastasalat med kylling og agurk",
    minutes: 25,
    category: "salat",
    childFriendly: true,
    allergens: ["gluten", "laktose"],
    seasonTags: ["sommer"],
    ingredients: [
      { ingredientId: "pasta_skruer", displayName: "pastaskruer", role: "bærende", amountText: "300 g" },
      { ingredientId: "kyllingebryst", displayName: "kyllingebryst", role: "bærende", amountText: "300 g" },
      { ingredientId: "skyr", displayName: "skyr", role: "bærende", amountText: "2 dl" },
      { ingredientId: "agurk", displayName: "agurk", role: "fleksibel", amountText: "1 stk" },
      { ingredientId: "pesto", displayName: "pesto", role: "fleksibel", amountText: "1 spsk" },
    ],
    steps: [
      "Kog pastaen og køl den af.",
      "Steg kyllingen gylden og skær den i skiver.",
      "Rør skyr og pesto sammen til en dressing.",
      "Vend pasta, kylling og agurk sammen.",
      "Smag til og servér koldt eller lunt.",
    ],
    approved: true,
  },
];
